In [1]:
import numpy as np

In [2]:
np.array(1)

array(1)

In [3]:
np.array([1,2,3])

array([1, 2, 3])

In [5]:
np.array([[1,2],
         [3,4],
         [5,6]])

array([[1, 2],
       [3, 4],
       [5, 6]])

In [16]:
array = np.array([1,2,3])
array

array([1, 2, 3])

In [13]:
array.shape

(3,)

In [23]:
array = np.array([[1,2],[3,4],[5,6]])
array

array([[1, 2],
       [3, 4],
       [5, 6]])

In [24]:
array.shape

(3, 2)

In [26]:
array.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
array.reshape(-1, 1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [28]:
array = np.array([[1, 2], [3, 4], [5, 6]])
array.ravel()

array([1, 2, 3, 4, 5, 6])

In [30]:
array = np.array([[1,2],[3,4],[5,6]])
array

array([[1, 2],
       [3, 4],
       [5, 6]])

In [31]:
array[0]

array([1, 2])

In [32]:
array[1:]

array([[3, 4],
       [5, 6]])

In [34]:
array[:2]

array([[1, 2],
       [3, 4]])

In [36]:
array[0,1]
#array[0][1]

2

In [38]:
array[:,1]

array([2, 4, 6])

In [40]:
array[:,0]

array([1, 3, 5])

In [41]:
array > 4

array([[False, False],
       [False, False],
       [ True,  True]])

In [42]:
array[array > 4]

array([5, 6])

In [76]:
x = np.arange(20).reshape(-1,1)
y = np.random.rand(20)
y

array([0.97676109, 0.60484552, 0.73926358, 0.03918779, 0.28280696,
       0.12019656, 0.2961402 , 0.11872772, 0.31798318, 0.41426299,
       0.0641475 , 0.69247212, 0.56660145, 0.26538949, 0.52324805,
       0.09394051, 0.5759465 , 0.9292962 , 0.31856895, 0.66741038])

In [77]:
y = np.where(y < .5,0,1)
y

array([1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1])

In [78]:
x[:][y == 1]

array([[ 0],
       [ 1],
       [ 2],
       [11],
       [12],
       [14],
       [16],
       [17],
       [19]])

In [51]:
array_1 = np.array([[1,2],[3,4],[5,6]])
array_2 = np.array([[7,8],[9,10],[11,12]])

np.vstack([array_1,array_2])

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [54]:
np.hstack([array_1,array_2])

array([[ 1,  2,  7,  8],
       [ 3,  4,  9, 10],
       [ 5,  6, 11, 12]])

In [55]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [57]:
array = np.array([[1, 2], [3, 4], [5, 6]])
np.zeros_like(array)

array([[0, 0],
       [0, 0],
       [0, 0]])

In [58]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [59]:
np.ones_like(array)

array([[1, 1],
       [1, 1],
       [1, 1]])

In [60]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [61]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

# 乱数の生成
### 乱数の生成には、主にrandn, rand, randintのいずれか使います。

####    randn: 標準正規分布（平均０，分散１）にしたがって乱数を生成
####    rand: ０から１までの範囲で乱数を生成
####   randint: 指定した範囲の整数をランダムに抽出
### 乱数を固定するためには、np.random.seed()を指定します。


In [62]:
np.random.seed(0)

In [67]:
np.random.randn(10)

array([ 1.23029068,  1.20237985, -0.38732682, -0.30230275, -1.04855297,
       -1.42001794, -1.70627019,  1.9507754 , -0.50965218, -0.4380743 ])

In [68]:
np.random.rand(10)

array([0.65310833, 0.2532916 , 0.46631077, 0.24442559, 0.15896958,
       0.11037514, 0.65632959, 0.13818295, 0.19658236, 0.36872517])

In [70]:
np.random.randint(0,100,10)

array([94,  0, 50, 36, 34, 48, 93,  3, 98, 42])

In [71]:
array_1 + array_2

array([[ 8, 10],
       [12, 14],
       [16, 18]])

In [72]:
array_1 - array_2

array([[-6, -6],
       [-6, -6],
       [-6, -6]])

In [73]:
array_1 / array_2

array([[0.14285714, 0.25      ],
       [0.33333333, 0.4       ],
       [0.45454545, 0.5       ]])

In [87]:
y = np.random.rand(20)
y = np.where(y < .5,0,1)
y

array([0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0])

In [92]:
np.where(y == 1)

(array([ 1,  3,  4,  5,  8, 10, 11, 12, 13, 16, 18]),)